### ISSUE TITLE
Reconnect when a disconnect happens, due to a mobile device going to sleep mode

### ISSUE THREAD

**Issue by tradiff** [LRFalk01/TimePoker#2]

**Comment by LRFalk01** [comment]
Fixed in commit https://github.com/LRFalk01/TimePoker/commit/39b4a3351b54f8565ad247f7a9f42001c5309df2

**Comment by benfalk** [comment]
![reconnect](https://cloud.githubusercontent.com/assets/2657901/6562679/25f40d7c-c669-11e4-8b51-89d5c32629e1.jpg)
