### ISSUE TITLE
Subtracting hours

### ISSUE THREAD

**Issue by ghost** [LRFalk01/TimePoker#4]
Would like to, can't :(

**Comment by benfalk** [comment]
![turn_back_time](https://cloud.githubusercontent.com/assets/2657901/6237631/14072cd4-b6ba-11e4-8413-5fb12f289a4d.gif)

**Comment by tradiff** [comment]
Simple workaround:  Just keep adding hours until you get a float overflow and it rolls over to negative numbers.  Should only take a couple of months to get back to where you want to be.

**Comment by benfalk** [comment]
where there's a will there's a way

**Comment by LRFalk01** [comment]
Ability added https://github.com/LRFalk01/TimePoker/commit/fe45c4ded235e948a6e15de89f51d147c6b0b54f
